const config = {
    MAPBOX_ACCESS_TOKEN: process.env.REACT_APP_MAPBOX_ACCESS_TOKEN,
    GOOGLE_TRACK: process.env.REACT_APP_GOOGLE_TRACK,
    APP_VERSION: process.env.REACT_APP_VERSION,
    REACT_APP_NAME: process.env.REACT_APP_NAME,
    GOOGLE_API_KEY: process.env.REACT_APP_GOOGLE_API_KEY,
    GOOGLE_FILE: process.env.REACT_APP_GOOGLE_FILE,
    GOOGLE_FILE_RIPETTA: process.env.REACT_APP_GOOGLE_FILE_RIPETTA,
    GOOGLE_CLIENT_ID: process.env.REACT_APP_GOOGLE_CLIENT_ID,
    GOOGLE_SECREAT_ID: process.env.REACT_APP_GOOGLE_SECREAT_ID,
    AUTH_REDIRECTION: process.env.REACT_APP_AUTH_REDIRECTION,
};

export default config;
